### PR TITLE
Rollup config

### PR DESCRIPTION
**Pull request by bash**
- [ ] Merge rollup configs
- [ ] Fix search/replace fuckups

### CODE REVIEW

**Comment by SirRade** [comment]
@bash is this ready for merging?

**Comment by bash** [comment]
@SirRade Not yet. I want to merge the two rollup configs first.

**Comment by bash** [comment]
@SirRade I'm cleaning my PRs and was wondering what your plans with `shootr` are and whether I should finish this PR or not...

**Comment by SirRade** [comment]
I'm definitely going to finish it right after https://github.com/SirRade/rust-standard-library-cookbook
I'm no Dean after all ;)

**Comment by bash** [comment]
Abandoning as discussed IRL.

**Pull request closed without merging**
